# This overlay uses CertManager to provision a certificate for the
# PodDefaults admission controller. This is preferred over the old
# way of using "bootstrap" which was running a shell script to create
# the certificate.
# TODO(jlewi): We should eventually refactor the manifests to delete
# bootstrap and use certmanager by default.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- certificate.yaml
- ../../base

namespace: kubeflow
namePrefix: admission-webhook-

generatorOptions:
  disableNameSuffixHash: true

labels:
- includeSelectors: true
  pairs:
    app: poddefaults
    app.kubernetes.io/component: poddefaults
    app.kubernetes.io/name: poddefaults
    kustomize.component: poddefaults

patches:
- path: mutating-webhook-configuration.yaml
- path: deployment.yaml

replacements:
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: service
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 0
    select:
      group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
      version: v1
  - fieldPaths:
    - spec.commonName
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 1
    select:
      group: cert-manager.io
      kind: Certificate
      name: cert
      version: v1
- source:
    fieldPath: metadata.name
    kind: Service
    name: service
    version: v1
  targets:
  - fieldPaths:
    - spec.commonName
    - spec.dnsNames.0
    - spec.dnsNames.1
    options:
      delimiter: .
      index: 0
    select:
      group: cert-manager.io
      kind: Certificate
      name: cert
      version: v1
- source:
    fieldPath: metadata.name
    group: cert-manager.io
    kind: Certificate
    name: cert
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
    select:
      group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      name: mutating-webhook-configuration
      version: v1
